### ISSUE TITLE
Ungenügende Fragen sammeln

### ISSUE THREAD

**Issue by 1423444** [keepcalmlerngerman/PMO-QM-LMS#1]
Bitte durchsuche das Dokument [Fragenzusammenfassung](https://github.com/keepcalmlerngerman/PMO-QM-LMS/blob/master/Vorbereitung-fuer-die-Fragenkatalogen/20160323_Zusammenfassung%20aller%20Fragen_V1) nach unnötigen, unverständlichen, oder fehlerhaften Fragen, sammle diese in einem Dokument und stelle es in Github. In diesem kannst du auch gleich Verbesserungsvorschläge machen. Bitte entferne diese Fragen aus dem ursprünglichen Dokument.

**Comment by tjuenemann** [comment]
Fragen überarbeitet.
