### ISSUE TITLE
Scrum Master

### ISSUE THREAD

**Issue by 1423444** [keepcalmlerngerman/PMO-QM-LMS#2]
Bitte prüfe das [Sprint Backlog](https://github.com/keepcalmlerngerman/PMO-QM-LMS/blob/master/Scrum%20Projektmanagement/Sprint%20Backlog/20160412_Sprint%20Backlog_QS_HJ_V3.md) und seine Versionen.
Beachte dabei, dass es einfach gehalten sein soll, womöglich sind zu viele Informationen enthalten.

Sind alle Versionen gecheckt füge bitte dein Namenskürzel nach meinem im Dokumentname zu.

**Comment by tjuenemann** [comment]
Erledigt.
