### ISSUE TITLE
Kontrolle

### ISSUE THREAD

**Issue by 1423444** [keepcalmlerngerman/PMO-QM-LMS#7]
Bitte prüfe das Dokument [Sprint Backlog](https://github.com/keepcalmlerngerman/PMO-QM-LMS/blob/master/Scrum%20Projektmanagement/Sprint%20Backlog/20160412_Sprint%20Backlog_QS_HJ_JT_HJ_V5.md). Beachte dabei Übereinstimmung der ID und der Kommentare mir Product Backlog. :smile:

**Comment by tjuenemann** [comment]
Alles in Ordnung.
